# Generated by Django 3.1.4 on 2021-01-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=13)),
                ('phone2', models.CharField(blank=True, max_length=13, null=True)),
                ('debts', models.FloatField(default=0)),
                ('difference', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': '7) Nasiyachilar',
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summa', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '6) Faktura',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '2) Filial',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '3.1) Group',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparer', models.CharField(max_length=255)),
                ('som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('kurs', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
            ],
            options={
                'verbose_name_plural': '3.2) Product',
            },
        ),
        migrations.CreateModel(
            name='ProductFilial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.FloatField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name_plural': '3.1) Product Filial',
            },
        ),
        migrations.CreateModel(
            name='Recieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summa', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '4) Recieve',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'saler'), (4, 'warehouse')], default=3)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name_plural': '1) User',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('naqd', models.FloatField(default=0)),
                ('plastik', models.FloatField(default=0)),
                ('nasiya', models.FloatField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('saler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': '5) Shop',
            },
        ),
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quan', models.FloatField(default=0)),
                ('summa', models.FloatField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': 'Return Product',
            },
        ),
        migrations.CreateModel(
            name='RecieveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('kurs', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('recieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recieve')),
            ],
            options={
                'verbose_name_plural': '4.1) RecieveItem',
            },
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name_plural': '9) Tolov Tarixi',
            },
        ),
        migrations.CreateModel(
            name='FakturaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name_plural': '6.1) FakturaItem',
            },
        ),
        migrations.AddField(
            model_name='faktura',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField()),
                ('debtorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Qarz Tarixi',
            },
        ),
        migrations.CreateModel(
            name='CartDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('given_quan', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('return_quan', models.FloatField(default=0)),
                ('return_sum', models.IntegerField(default=0)),
                ('debt_quan', models.FloatField(default=0)),
                ('debt_sum', models.FloatField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': 'CartDebt',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
            options={
                'verbose_name_plural': '5.1) Cart',
            },
        ),
    ]
