# Generated by Django 3.1.4 on 2021-01-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturaitem',
            name='debt_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='debt_price',
            field=models.FloatField(default=15000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartdebt',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartdebt',
            name='return_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='difference',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fakturaitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='sum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productfilial',
            name='price',
            field=models.FloatField(),
        ),
    ]
