# Generated by Django 3.1.4 on 2021-02-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210127_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodFaktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summa', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name_plural': '6) WoodFaktura',
            },
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='difference',
            new_name='m_difference',
        ),
        migrations.AddField(
            model_name='fakturaitem',
            name='barcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='p_difference',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='WoodFakturaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('debt_price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('woodfaktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.woodfaktura')),
            ],
            options={
                'verbose_name_plural': '6.1) WoodFakturaItem',
            },
        ),
    ]
