# Generated by Django 3.1.4 on 2021-02-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210202_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='m_difference',
            new_name='difference',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='p_difference',
        ),
    ]
