# Generated by Django 3.1.4 on 2021-02-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210205_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturaitem',
            name='name',
            field=models.CharField(default='2020-12-12T00:00:00', max_length=255),
            preserve_default=False,
        ),
    ]
