# Generated by Django 3.1.4 on 2021-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fakturaitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='barcode',
            field=models.CharField(default='2020-12-12T00:00:00', max_length=255),
            preserve_default=False,
        ),
    ]
