# Generated by Django 3.1.4 on 2021-02-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_faktura_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='barcode',
        ),
    ]
