# Generated by Django 3.1.4 on 2021-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_faktura_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='difference',
            field=models.IntegerField(default=0),
        ),
    ]
