# Generated by Django 3.1.4 on 2021-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210205_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='barcode',
            field=models.CharField(default=10101010, max_length=255),
            preserve_default=False,
        ),
    ]
