# Generated by Django 3.1.4 on 2021-02-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productfilial_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='barcode',
            field=models.CharField(default=10000000, max_length=255),
            preserve_default=False,
        ),
    ]
