# Generated by Django 3.1.4 on 2021-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210208_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='transfer',
            field=models.FloatField(default=0),
        ),
    ]
