# Generated by Django 3.1.4 on 2021-02-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_shop_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dollar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groups'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kurs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
