# Generated by Django 3.1.4 on 2021-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210208_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='deliver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recieve',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
