# Generated by Django 3.1.4 on 2021-02-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210211_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve',
            name='deliver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
