# Generated by Django 3.1.4 on 2021-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210211_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recieve',
            name='deliver',
        ),
    ]
