# Generated by Django 3.1.4 on 2021-02-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_recieve_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='deliver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.deliver'),
            preserve_default=False,
        ),
    ]
