# Generated by Django 3.1.4 on 2021-02-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210212_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otkaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summa', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Otkaz',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='debtor',
            options={'verbose_name_plural': 'Nasiyachilar'},
        ),
        migrations.AlterModelOptions(
            name='deliver',
            options={'verbose_name_plural': 'Deliver'},
        ),
        migrations.AlterModelOptions(
            name='faktura',
            options={'verbose_name_plural': 'Faktura'},
        ),
        migrations.AlterModelOptions(
            name='fakturaitem',
            options={'verbose_name_plural': 'FakturaItem'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name_plural': 'Filial'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='payhistory',
            options={'verbose_name_plural': 'Tolov Tarixi'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productfilial',
            options={'verbose_name_plural': 'Product Filial'},
        ),
        migrations.AlterModelOptions(
            name='recieve',
            options={'verbose_name_plural': 'Recieve'},
        ),
        migrations.AlterModelOptions(
            name='recieveitem',
            options={'verbose_name_plural': 'RecieveItem'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': 'Shop'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='woodfaktura',
            options={'verbose_name_plural': 'WoodFaktura'},
        ),
        migrations.AlterModelOptions(
            name='woodfakturaitem',
            options={'verbose_name_plural': 'WoodFakturaItem'},
        ),
        migrations.CreateModel(
            name='OtkazItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('otkaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otkaz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name_plural': 'OtkazItem',
            },
        ),
        migrations.AddField(
            model_name='otkaz',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
