# Generated by Django 3.1.4 on 2021-02-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210212_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otkaz',
            name='summa',
        ),
    ]
