from rest_framework.routers import DefaultRouter
from .viewsets import *

router = DefaultRouter()
# router.register('token', TokenViewset)
router.register('userprofile', UserProfileViewset)
router.register('filial', FilialViewset)
router.register('groups', GroupsViewset)
router.register('deliver', DeliverViewset)
router.register('product', ProductViewset)
router.register('product100', Product100Viewset)
router.register('productfilial', ProductFilialViewset)
router.register('recieve', RecieveViewset)
router.register('recieveitem', RecieveItemViewset)
router.register('faktura', FakturaViewset)
router.register('fakturaitem', FakturaItemViewset)
router.register('otkaz', OtkazViewset)
router.register('otkazitem', OtkazItemViewset)
router.register('woodfaktura', WoodFakturaViewset)
router.register('woodfakturaitem', WoodFakturaItemViewset)
router.register('shop', ShopViewset)
router.register('cart', CartViewset)
router.register('debtor', DebtorViewset)
# router.register('debthistory', DebtHistoryViewset)
router.register('debt', DebtViewset)
router.register('payhistory', PayHistoryViewset)
router.register('cartdebt', CartDebtViewset)
router.register('returnproduct', ReturnProductViewset)
